USE [master]
GO

/****** Object:  Database [tetris]    Script Date: 2024/12/21 上午 04:35:19 ******/
CREATE DATABASE [tetris]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'tetris', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\tetris.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'tetris_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\tetris_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [tetris].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [tetris] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [tetris] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [tetris] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [tetris] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [tetris] SET ARITHABORT OFF 
GO

ALTER DATABASE [tetris] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [tetris] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [tetris] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [tetris] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [tetris] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [tetris] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [tetris] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [tetris] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [tetris] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [tetris] SET  DISABLE_BROKER 
GO

ALTER DATABASE [tetris] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [tetris] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [tetris] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [tetris] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [tetris] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [tetris] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [tetris] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [tetris] SET RECOVERY FULL 
GO

ALTER DATABASE [tetris] SET  MULTI_USER 
GO

ALTER DATABASE [tetris] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [tetris] SET DB_CHAINING OFF 
GO

ALTER DATABASE [tetris] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [tetris] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [tetris] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [tetris] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [tetris] SET QUERY_STORE = ON
GO

ALTER DATABASE [tetris] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [tetris] SET  READ_WRITE 
GO

